version: '3.1'

services:

  wordpress:
    depends_on:
      - db${SHORTNAME}
    image: spoluprace/wordpress:latest
    restart: always
    expose:
      - 80
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST},www.${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST},www.${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: spoluprace@martinkokes.cz
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 0
    volumes:
      - ./web:/var/www/html
      - ./php-conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  db${SHORTNAME}:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: thisnotuseduserhahaha
    volumes:
      - db${SHORTNAME}:/var/lib/mysql

volumes:
    db${SHORTNAME}:
    
networks:
  default:
    external:
      name: nginx-proxy
