version: '3.1'

services:

  wordpress:
    depends_on:
      - db
    links:
      - db:${CUSTOM_ALIAS}srv
    image: wordpress:5.7-php8.0-apache
    restart: always
    expose:
      - 80
    environment:
      WORDPRESS_DB_HOST: ${CUSTOM_ALIAS}srv:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      WORDPRESS_DB_NAME: ${CUSTOM_ALIAS}db
      WORDPRESS_DEBUG: 0
    volumes:
      - ./web:/var/www/html
      #- ${PWD}/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${CUSTOM_ALIAS}db
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      command: --innodb_use_native_aio=0
    volumes:
      - db:/var/lib/mysql

volumes:
    db:
    
networks:
  default:
    external:
      name: nginxproxymanager_default
