version: '3.1'

services:

  wordpress:
    depends_on:
      - db
    image: wordpress:5.7.0-php8.0-apache
    restart: always
    expose:
      - 80
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST},www.${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST},www.${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: spoluprace@martinkokes.cz
      WORDPRESS_DB_HOST: db:${DATABASE_PORT}
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 0
    volumes:
      - ./web:/var/www/html
      - ./php-conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: thisnotuseduserhahaha
    volumes:
      - db:/var/lib/mysql
#    ports:
#      - ${DATABASE_PORT}:3306

volumes:
    db:
    
networks:
  default:
    external:
      name: nginx-proxy
